### ISSUE TITLE
Users cannot suggest edits

### ISSUE THREAD

**Issue by m-clare** [aecworks/aec.works-api#93]
Tried adding a new hashtag to an existing company and received the following error, despite this being my first attempted edit of an existing company:

'nonFieldError: non-editor user exceeded limit of unmoderated edits'

<img width="606" alt="image" src="https://user-images.githubusercontent.com/6874646/117562132-87ac7d00-b051-11eb-8ea1-33464d5da770.png">

**Comment by gtalarico** [comment]
This is by design.

Currently users (non-editors)
can have up to 1 unmoderated submissions.
Once it's approved you can submit more.
You already have a pending one ('Toggle Industries')

Currently shows as an error. 
We should show a friendlier message or reconsider the process. Maybe we can allow more, like 3-5.
I just wanted to start Conservative.

https://github.com/aecworks/aec.works-api/blob/18037839d15b07e7f9cd8005591ade1ff11c5bcb/api/community/services.py#L168

**Comment by gtalarico** [comment]
And view: 
https://github.com/aecworks/aec.works-api/blob/master/api/community/views/company_revisions.py

I think we should increase to at least 2.
I just didn't want to get flooded with reviews since we don't have many editors active yet
